### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by hemanu** [petroGG/Basic-Well-Log-Interpretation#1]
when you define the vclgr function in the section In [15], the function parameters are gr_log, gr_clean, gr_clay, of course you declare them in the section In [23]: gr_clean, gr_clay, etc. My question is where do you declare gr_log, sp_log, neut_log, etc.?

**Comment by hemanu** [comment]
![section 15](https://user-images.githubusercontent.com/14192438/38282109-f14fcdf2-3773-11e8-8333-f08ee9f94f15.JPG)

![section 23](https://user-images.githubusercontent.com/14192438/38282153-3ffca66e-3774-11e8-8019-2063116370f4.JPG)

**Comment by petroGG** [comment]
Gr_log, sp_log, neut_log - represent your GR, SP and Neutronic logs. They are imported in section In [10] with the following command:
 data=pd.read_table('WA1.txt', delim_whitespace=True, index_col='M__DEPTH'),
 and then reduced to my zone of interest (which is between top_depth and bottom_depth variables) with:
 logs=data[(data.DEPT >= top_depth) & (data.DEPT <= bottom_depth)]
So any log is imported as a pandas series that can be called with logs.GR, logs.SP, logs. NPHI ... 

Vclgr, vclnd and vclsp are calculated all at once in a loop in section In [23]:
for (i,j,k,l,m) in zip(logs.GR,logs.NPHI,logs.RHOB,logs.ILD,logs.SP):
    vclgr_temp.append(vclgr(i, gr_clean, gr_clay))
    vclnd_temp.append(vclnd(j,k,neut_clean1,den_clean1,neut_clean2,den_clean2,neut_clay,den_clay))
    vclsp_temp.append(vclsp(m, sp_clean, sp_clay))

PS. There is very good library to import your las files into lists or pandas dataframe called lasio.
