### ISSUE TITLE
name 'ax' is not defined

### ISSUE THREAD

**Issue by lourawirawan** [petroGG/Basic-Well-Log-Interpretation#3]
after i try run the program until 
>>triple_combo_plot(data.DEPT.min(),data.DEPT.max())
the result only well composit with nothing inside. only the square line and title "well composite. because  "NameError: name 'ax' is not defined" appear.  could you help? because im new to programming. 
![111](https://user-images.githubusercontent.com/63727412/79687105-44fce480-8245-11ea-91dd-63f6a56b505a.JPG)

**Comment by Philliec459** [comment]
I have used Mihai's PetroGG as the basis to create a couple of repositories basically related to shaley sand analysis where I have added Qv from Swb using Hill, Shirley and Klein relationship with some other changes. try the notebooks in these repositories to see if this works for you and then determine the problem.

https://github.com/Philliec459/PetroGG-for-NMR-shaly-sand-Data
https://github.com/Philliec459/PetroGG-Modified-for-Shaly-Sand-Interpretation

**Comment by Philliec459** [comment]
your definition of tops is right in the middle of the definition of the triple combo. Please see how I did this in my repositories. they should be similar

![image](https://user-images.githubusercontent.com/56929340/79693922-a794b700-822a-11ea-96b7-39c0ea07eb5e.png)

**Comment by petroGG** [comment]
Please run the cells in their order and keep the entire triple_combo_plot function code in a single cell when you run it (as in the original notebook) and everything will work fine.

**Comment by lourawirawan** [comment]
Thank you so much.. it runs perfectly right now.  hope you have a nice day.
:)
